list = [1,2,3,4,5,6,7]
print(list)
list.append(8)
print(list)
list.insert(1,9)
print(list)
list2 = list.copy()
print(list2)
li = ('A','B')
list.extend(li)
print(list)
print(list.count(1))
list.remove('A')
print(list)
list.pop(9)
print(list)
list.sort()
print(list)
list.reverse()
print(list)
list.clear()
print(list)